{
    "kind": "Listing",
    "data": {
        "after": "t3_84bztk",
        "dist": 1,
        "modhash": "",
        "whitelist_status": null,
        "children": [{
            "kind": "t3",
            "data": {
                "subreddit_id": "t5_2qh1b",
                "approved_at_utc": null,
                "send_replies": false,
                "mod_reason_by": null,
                "banned_by": null,
                "num_reports": null,
                "removal_reason": null,
                "thumbnail_width": 140,
                "subreddit": "microsoft",
                "selftext_html": null,
                "selftext": "",
                "likes": null,
                "suggested_sort": null,
                "user_reports": [],
                "secure_media": null,
                "is_reddit_media_domain": false,
                "saved": false,
                "id": "84bztk",
                "banned_at_utc": null,
                "mod_reason_title": null,
                "view_count": null,
                "archived": false,
                "clicked": false,
                "no_follow": false,
                "author": "gruberjl",
                "num_crossposts": 0,
                "link_flair_text": null,
                "mod_reports": [],
                "can_mod_post": false,
                "is_crosspostable": false,
                "pinned": false,
                "score": 7,
                "approved_by": null,
                "over_18": false,
                "report_reasons": null,
                "domain": "blogs.microsoft.com",
                "hidden": false,
                "preview": {
                    "images": [{
                        "source": {
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fm=jpg&amp;s=39ea2edd996ca228dfa2685700d91667",
                            "width": 960,
                            "height": 540
                        },
                        "resolutions": [{
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;fm=jpg&amp;s=c7eb2febf8e957aa6734634b6316d3df",
                            "width": 108,
                            "height": 60
                        }, {
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;fm=jpg&amp;s=fce2580cc96230c2362f6b4b65dc02b9",
                            "width": 216,
                            "height": 121
                        }, {
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;fm=jpg&amp;s=45dd121cb3b2c9a116f6b9c82c1b24ec",
                            "width": 320,
                            "height": 180
                        }, {
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;fm=jpg&amp;s=2ad6697415ee68201d8d981b1b65baba",
                            "width": 640,
                            "height": 360
                        }, {
                            "url": "https://i.redditmedia.com/n37GhOCVekd47jw2uT7jkjjebxYieRsPThsx-9P76f4.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;fm=jpg&amp;s=9457cebc2b5c27fc5ad0ce7d732f18d9",
                            "width": 960,
                            "height": 540
                        }],
                        "variants": {},
                        "id": "5dyMXwebqvCH3VX5g1B6F9PRaZViakkOTkJnZhrN_dE"
                    }],
                    "enabled": false
                },
                "thumbnail": "https://b.thumbs.redditmedia.com/fLC9NbAeNHPooGYtCMcFqrtVo6EOF5E5t6qiYGoAZCM.jpg",
                "edited": false,
                "link_flair_css_class": null,
                "author_flair_css_class": null,
                "contest_mode": false,
                "gilded": 0,
                "downs": 0,
                "brand_safe": true,
                "secure_media_embed": {},
                "media_embed": {},
                "post_hint": "link",
                "author_flair_text": null,
                "stickied": false,
                "visited": false,
                "can_gild": false,
                "thumbnail_height": 78,
                "parent_whitelist_status": "all_ads",
                "name": "t3_84bztk",
                "spoiler": false,
                "permalink": "/r/microsoft/comments/84bztk/microsoft_expands_cloud_services_in_europe_and/",
                "subreddit_type": "public",
                "locked": false,
                "hide_score": false,
                "created": 1521047547.0,
                "url": "https://blogs.microsoft.com/blog/2018/03/14/microsoft-expands-cloud-services-in-europe-and-into-middle-east-to-meet-growing-customer-demand/",
                "whitelist_status": "all_ads",
                "quarantine": false,
                "subreddit_subscribers": 50542,
                "created_utc": 1521018747.0,
                "subreddit_name_prefixed": "r/microsoft",
                "ups": 7,
                "media": null,
                "num_comments": 0,
                "is_self": false,
                "title": "Microsoft expands cloud services in Europe and into Middle East to meet growing customer demand",
                "mod_note": null,
                "is_video": false,
                "distinguished": null
            }
        }],
        "before": null
    }
}
