module.exports = {
  name: [
    'Jennifer Hall',
    'Elizabeth Wood',
    'Linda Lewis',
    'Tyler West',
    'Henry Webb',
    'Douglas Washington',
    'Jose Warren',
    'Peter Wallace',
    'Adam Tucker',
    'Zachary Sullivan',
    'Nathan Stevens',
    'Walter Simpson',
    'Harold Simmons',
    'Kyle Russell',
    'Carl Reynolds',
    'Arthur Reyes',
    'Gerald Ramos',
    'Roger Powell',
    'Keith Porter',
    'Jeremy Patterson',
    'Terry Owens',
    'Lawrence Ortiz',
    'Sean Myers',
    'Christian Murray',
    'Albert Morales',
    'Joe Mcdonald',
    'Ethan Mason',
    'Austin Marshall',
    'Jesse Long',
    'Willie Kennedy',
    'Billy Jordan',
    'Bryan Hunter',
    'Bruce Hughes',
    'Jordan Hicks',
    'Ralph Henry',
    'Roy Hayes',
    'Noah Harrison',
    'Dylan Hamilton',
    'Eugene Griffin',
    'Wayne Graham',
    'Emma Gonzales',
    'Maria Gomez',
    'Heather Gibson',
    'Diane Freeman',
    'Julie Foster',
    'Joyce Ford',
    'Evelyn Flores',
    'Frances Fisher',
    'Joan Ellis',
    'Christina Dixon',
    'Kelly Diaz',
    'Victoria Cruz',
    'Lauren Crawford',
    'Martha Cole',
    'Judith Butler',
    'Cheryl Burns',
    'Megan Bryant',
    'Andrea Boyd',
    'Ann Alexander',
    'Alice Ford',
    'Jean Flores',
    'Doris Fisher',
    'Jacqueline Ellis',
    'Kathryn Dixon',
    'Hannah Diaz',
    'Olivia Cruz',
    'Gloria Crawford',
    'Marie Cole',
    'Teresa Butler',
    'Sara Hughes',
    'Janice Hicks',
    'Julia Henry',
    'Grace Hayes',
    'Judy Harrison',
    'Theresa Hamilton',
    'Rose Griffin',
    'Beverly Graham',
    'Denise Crawford',
    'Marilyn Cole'
  ],
  email: [
    'Jennifer.Hall@gitbit.org',
    'Elizabeth.Wood@gitbit.org',
    'Linda.Lewis@gitbit.org',
    'Tyler.West@gitbit.org',
    'Henry.Webb@gitbit.org',
    'Douglas.Washington@gitbit.org',
    'Jose.Warren@gitbit.org',
    'Peter.Wallace@gitbit.org',
    'Adam.Tucker@gitbit.org',
    'Zachary.Sullivan@gitbit.org',
    'Nathan.Stevens@gitbit.org',
    'Walter.Simpson@gitbit.org',
    'Harold.Simmons@gitbit.org',
    'Kyle.Russell@gitbit.org',
    'Carl.Reynolds@gitbit.org',
    'Arthur.Reyes@gitbit.org',
    'Gerald.Ramos@gitbit.org',
    'Roger.Powell@gitbit.org',
    'Keith.Porter@gitbit.org',
    'Jeremy.Patterson@gitbit.org',
    'Terry.Owens@gitbit.org',
    'Lawrence.Ortiz@gitbit.org',
    'Sean.Myers@gitbit.org',
    'Christian.Murray@gitbit.org',
    'Albert.Morales@gitbit.org',
    'Joe.Mcdonald@gitbit.org',
    'Ethan.Mason@gitbit.org',
    'Austin.Marshall@gitbit.org',
    'Jesse.Long@gitbit.org',
    'Willie.Kennedy@gitbit.org',
    'Billy.Jordan@gitbit.org',
    'Bryan.Hunter@gitbit.org',
    'Bruce.Hughes@gitbit.org',
    'Jordan.Hicks@gitbit.org',
    'Ralph.Henry@gitbit.org',
    'Roy.Hayes@gitbit.org',
    'Noah.Harrison@gitbit.org',
    'Dylan.Hamilton@gitbit.org',
    'Eugene.Griffin@gitbit.org',
    'Wayne.Graham@gitbit.org',
    'Emma.Gonzales@gitbit.org',
    'Maria.Gomez@gitbit.org',
    'Heather.Gibson@gitbit.org',
    'Diane.Freeman@gitbit.org',
    'Julie.Foster@gitbit.org',
    'Joyce.Ford@gitbit.org',
    'Evelyn.Flores@gitbit.org',
    'Frances.Fisher@gitbit.org',
    'Joan.Ellis@gitbit.org',
    'Christina.Dixon@gitbit.org',
    'Kelly.Diaz@gitbit.org',
    'Victoria.Cruz@gitbit.org',
    'Lauren.Crawford@gitbit.org',
    'Martha.Cole@gitbit.org',
    'Judith.Butler@gitbit.org',
    'Cheryl.Burns@gitbit.org',
    'Megan.Bryant@gitbit.org',
    'Andrea.Boyd@gitbit.org',
    'Ann.Alexander@gitbit.org',
    'Alice.Ford@gitbit.org',
    'Jean.Flores@gitbit.org',
    'Doris.Fisher@gitbit.org',
    'Jacqueline.Ellis@gitbit.org',
    'Kathryn.Dixon@gitbit.org',
    'Hannah.Diaz@gitbit.org',
    'Olivia.Cruz@gitbit.org',
    'Gloria.Crawford@gitbit.org',
    'Marie.Cole@gitbit.org',
    'Teresa.Butler@gitbit.org',
    'Sara.Hughes@gitbit.org',
    'Janice.Hicks@gitbit.org',
    'Julia.Henry@gitbit.org',
    'Grace.Hayes@gitbit.org',
    'Judy.Harrison@gitbit.org',
    'Theresa.Hamilton@gitbit.org',
    'Rose.Griffin@gitbit.org',
    'Beverly.Graham@gitbit.org',
    'Denise.Crawford@gitbit.org',
    'Marilyn.Cole@gitbit.org'
  ]
}
